name: weatherapp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  shared_preferences: ^2.0.15
  shared_preferences_web: ^2.0.0
  flutter_email_sender: ^5.0.2
  geolocator: ^9.0.1
  http: ^1.2.2
  responsive_framework: ^0.1.0
  provider: ^6.0.5
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.8.0


flutter:

  
  uses-material-design: true

 
